export const DEFAULT_CONFIG = {
  title: "Live Tracker",
  trackFile: "tracks/start.gpx",
  translationFile: "translations/en.json",
  traccarUrl: null,
  token: null,
  debug: false,
  refreshSeconds: 10,
  deviceIds: null,
  showViewerLocation: false,
  staleMinutes: 15,
  startTime: null,
  debugStartTime: null,
  expectedAvgSpeedKph: 60,
  showKmMarkers: true,
  showWaypoints: true,
  historyHours: 24,
};

export const KM_MARKER_BASE_KM = 2;

export const DEFAULT_TEXTS = {
  eta: "ETA",
  etaHere: "ETA here: {eta}",
  etaMargin: "±{minutes} min",
  etaMarginSubMinute: "±<1 min",
  passed: "passed",
  offtrack: "participant not on track",
  unknown: "unknown",
  next: "Next",
  offrouteLabel: "off-route",
  startLabel: "start",
  finishLabel: "finish",
  historyTitle: "Progress",
  historyKm: "Distance ticks",
  historyKmDistance: "Distance",
  historyTime: "Time",
  historyAvgSpeed: "Avg speed",
  historyWp: "Waypoints",
  historyWpName: "Waypoint",
  historyWpEnter: "Entered",
  historyWpLeave: "Left",
  historyUpcoming: "Upcoming waypoints",
  historyEta: "ETA",
  historyDistanceTo: "Distance to",
  historyUpdated: "Updated",
  historyNone: "None yet",
  historyShow: "Show history",
  helpTip:
    "Select a participant to see live ETAs to waypoints. Right-click or long-press the map for Google Maps/Waze/coords and ETA to that point.",
  helpTitle: "Live Tracker Tips",
  toggleKm: "Show km markers",
  toggleWp: "Show waypoints",
  copyCoords: "Copy coordinates",
  openGoogle: "Open in Google Maps",
  openWaze: "Open in Waze",
  you: "You",
  toggleYou: "Show your location",
  downloadGpx: "Download GPX",
  weatherTitle: "Weather",
  weatherFetching: "Loading weather…",
  weatherUnavailable: "Weather unavailable",
  weatherWind: "Wind",
  weatherPrecip: "Rain",
  weatherNextHours: "Forecast",
  weatherPrev: "Prev",
  weatherNext: "Next",
  closeLabel: "Close",
  legend: "Legend",
  options: "Options",
  gain: "Gain",
  descent: "Descent",
  countdownStartsIn: "Starts in",
  countdownStartAt: "Start: {time}",
  countdownOverlayHeading: "Event starts soon",
  countdownOverlayDismiss: "Close for now",
  countdownOverlayNever: "Don't show this again",
  debugTimeLabel: "Debug time",
  debugTimeApply: "Apply",
  debugTimeTicking: "Ticking",
  debugTimeFrozen: "Frozen",
};

export const TRANSLATIONS_MAP = {
  en: "translations/en.json",
  nl: "translations/nl.json",
  sv: "translations/sv.json",
};

export const LANGUAGE_COOKIE = "tracker_lang";
export const HISTORY_WINDOW_MS = 60 * 60 * 1000; // 1 hour
export const ACTIVE_DISTANCE_THRESHOLD = 50; // meters from start
